# Shell variables
# Generated by 'wal'
wallpaper='/home/tux/Pictures/n.png'

# Special
background='#0a0b0d'
foreground='#c3c8cc'
cursor='#c3c8cc'

# Colors
color0='#0a0b0d'
color1='#545C68'
color2='#997D5A'
color3='#375E8A'
color4='#577290'
color5='#718AA3'
color6='#779AC3'
color7='#c3c8cc'
color8='#888c8e'
color9='#545C68'
color10='#997D5A'
color11='#375E8A'
color12='#577290'
color13='#718AA3'
color14='#779AC3'
color15='#c3c8cc'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
