--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/tux/Pictures/n.png"

-- Special
background="#0a0b0d"
foreground="#c3c8cc"
cursor="#c3c8cc"

-- Colors
color0="#0a0b0d"
color1="#545C68"
color2="#997D5A"
color3="#375E8A"
color4="#577290"
color5="#718AA3"
color6="#779AC3"
color7="#c3c8cc"
color8="#888c8e"
color9="#545C68"
color10="#997D5A"
color11="#375E8A"
color12="#577290"
color13="#718AA3"
color14="#779AC3"
color15="#c3c8cc"
